# Generated by Django 4.2.3 on 2023-07-20 16:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dishtype",
            old_name="type",
            new_name="name",
        ),
    ]
