# Generated by Django 4.2.3 on 2023-07-21 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0002_rename_type_dishtype_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="finished_cooks",
            field=models.ManyToManyField(
                related_name="dishes_finished", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
