# Generated by Django 4.2.3 on 2023-07-24 15:41

import django.contrib.auth.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_alter_dish_description'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cook',
            managers=[
                ('custom_objects', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
